### PR TITLE
Hotfix usermanager 

### PR DESCRIPTION
**Pull request by duncdrum**
small refactor: uses the dashboard pane on 5.x, and the independent app on 4.x.
adjusted some dom selectors to be easier to comprehend

i've run this against 5.x from `develop` and we are in the green
4.x from `master` currently has no dashboard, so test are failing

for the failing monex test see eXist-db/monex#78

### CODE REVIEW

**Comment by joewiz** [comment]
Sorry, what does "no uses" mean?

**Comment by duncdrum** [comment]
i tried to say `now`

**Comment by duncdrum** [comment]
ok with the fixes to dashboard-1.x 
only monex index-test is failing (on both 4.x and 5.x):
Screenshot 2019-04-26 at 15 44 03
Screenshot 2019-04-26 at 15 44 20

**Comment by duncdrum** [comment]
monex fix is at eXist-db/monex#83

**Pull request merged**
