### PR TITLE
expand monex tesing

### PR DESCRIPTION
**Pull request by duncdrum**
enables previously failing monex tests

depends on eXist-db/monex#75

### CODE REVIEW

**Comment by duncdrum** [comment]
I suspect that the failing CI is due to the limitation on encrypted env variables in PR builds, you can see the [branch builds](https://github.com/duncdrum/e2e-core/commits/monex-fixes) in my branch not erroring out.

**Comment by joewiz** [comment]
As discussed in today's Community Call, we can expect failures like this until tests are migrated to their respective repos.

**Comment by joewiz** [comment]
@duncdrum Darn! I see the build is still failing even after merging. https://travis-ci.com/eXist-db/e2e-core/builds/106573478

**Comment by line-o** [comment]
@duncdrum @joewiz it always fails with `Uncaught ReferenceError: JMX is not defined`
Isn't monex broken on Existdb 5.0.0 because of something related to that?
It looks odd to me that both tests appear to go against 5 > `image=exist/existdb:latest`

**Comment by duncdrum** [comment]
@line-o @joewiz these test failures are accurate, and WAI. [The updates](eXist-db/monex#74) to monex have been merged, but there hasn't been a new release of the app yet. So exist is still shipping with the latest release, so the test failures are to be expected.

**Pull request merged**
