### PR TITLE
feat(monex): add index pages

### PR DESCRIPTION
**Pull request by duncdrum**
catches console error "Can't find variable: JMX	Global Code"

see eXist-db/monex#60

### CODE REVIEW

**Comment by duncdrum** [comment]
ping @eXist-db/xquery-contributors

**Comment by joewiz** [comment]
@duncdrum Could you first please address the failing tests?

**Comment by duncdrum** [comment]
@joewiz the test shows the actual behaviour of exist, in other words its working. The fix is with monex

**Comment by joewiz** [comment]
@duncdrum Could you please also file an issue in monex with an explicit description of the error implicitly demonstrated here?

**Comment by joewiz** [comment]
Sorry, I see the link in your original post. I guess what I mean is why are you asking for a review of this PR here if the issue isn't fixed in monex? Wouldn't that be the proper place to ping?

**Comment by joewiz** [comment]
Also, I could swear that it said the tests were failing, but now it's showing that the tests are passing. Am I going crazy?

**Comment by joewiz** [comment]
https://github.com/eXist-db/e2e-core/pull/3/checks shows that the build had indeed been failing but is now passing as of 30 minutes ago. 

So this PR is ok to merge from your perspective and no other action is needed in monex before this can be merged? If you confirm this, then I think we can actually review the PR.

**Comment by duncdrum** [comment]
@joewiz no when i opened the PR they showed the then showstopper bug for monex on 5.0-RC so the test was red, the showstopper has been fixed in the mean time so the test is now green. It was ready to merge when it was red, because it was correclty showing a problem. All good now from my end

**Comment by duncdrum** [comment]
ping @eXist-db/xquery-contributors

**Pull request merged**
